name: Deploy to Cloud Run

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: lumaai-12b32

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Build & Push Docker image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/lumaai-12b32/luma-backend-docker-repo/my-app:$GITHUB_SHA .
          docker push asia-southeast1-docker.pkg.dev/lumaai-12b32/luma-backend-docker-repo/my-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy lumaai-backend \
            --image asia-southeast1-docker.pkg.dev/lumaai-12b32/luma-backend-docker-repo/my-app:$GITHUB_SHA \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated
