name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: lumaai-12b32

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Access Firebase Database URL secret
        id: get_db_url
        run: echo "::set-output name=DATABASE_URL::$(gcloud secrets versions access latest --secret=DATABASE_URL)"

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Build & Push Docker image
        run: |
          docker build -t asia-southeast1-docker.pkg.dev/lumaai-12b32/luma-backend-docker-repo/my-app:$GITHUB_SHA .
          docker push asia-southeast1-docker.pkg.dev/lumaai-12b32/luma-backend-docker-repo/my-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy lumaai-backend \
            --image asia-southeast1-docker.pkg.dev/lumaai-12b32/luma-backend-docker-repo/my-app:$GITHUB_SHA \
            --platform managed \
            --region asia-southeast1 \
            --service-account github-cloud-run@lumaai-12b32.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --set-env-vars SPRING_PROFILES_ACTIVE=prod,DATABASE_URL=${{ steps.get_db_url.outputs.DATABASE_URL }}
